version: '3.9'

services:
  backend:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .

  db:
    image: postgres
    # restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_USER: user
      POSTGRES_DB: bmt


secrets:
   db_password:
     file: db_password.txt
